### ISSUE TITLE
Font size too big in task name

### ISSUE THREAD

**Issue by cdvr27** [kenlog/Oxygen#1]
Hi @kenlog . First of all, I apologize if I´m using "issues" in an unappropriated way, this is the first time I use GitHub.
I really liked Oxygen, it gives Kanboard a modern beautfull interface. Congratulations!
I have one question: I would like to change the font size of the task name in project board view (make it smaller). Can I customize it? How can I do that?
Thanks in advance!

**Comment by kenlog** [comment]
Hi @Claytondiver, I'm glad you like it. To change the text size of the task title, you can do this by pasting this code ```.task-board-title {
    font-size: 15px!important;
}``` in the application settings> Custom style sheet. In this way the title will be set to 15px or as you prefer, changing the value.

**In the next release I expect to add other interesting features.**
