### ISSUE TITLE
Plugin Makes Code in Hover Window Unreadable

### ISSUE THREAD

**Issue by bonesmoses** [kenlog/Oxygen#2]
In the Board view, hovering over a task's notepad icon brings up a temporary rendered sample of a ticket. At least in version 1.2.6 of Kanboard, the code itself appears as white outlined words that are very difficult to read.

See attached screenshot.

![capture](https://user-images.githubusercontent.com/719860/47260577-c7a3b880-d483-11e8-9ce3-838886867db4.PNG)

**Comment by kenlog** [comment]
Hello bonesmoses, thanks for the message. Today I release a new version that solves.
